"""
Multi-branch feature extraction for AI vs Real image detection.

Four branches:
  1. CLIP (semantic)    — OpenCLIP ViT-L/14, 768-dim L2-normalized embedding
  2. EfficientNet       — timm EfficientNetV2-L intermediate features, GAP → 1280-dim
  3. FFT (frequency)    — 2D FFT magnitude spectrum statistics → 8-dim
  4. SRM (noise)        — Spatial Rich Model residual filter statistics → 15-dim

Each branch extracts independently; a combiner normalizes per-block,
optionally applies PCA, and concatenates into a single vector.
"""

import logging
import os
import pickle
from typing import Optional

import cv2
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from scipy.stats import kurtosis, skew, entropy as sp_entropy

logger = logging.getLogger("visionprobe.detector.feature_extractors")

# ---------------------------------------------------------------------------
# ImageNet normalization
# ---------------------------------------------------------------------------
IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)

# ---------------------------------------------------------------------------
# SRM filter kernels (3×3)
# ---------------------------------------------------------------------------
SRM_FILTERS = [
    np.array([[0, 0, 0], [-1, 0, 1], [0, 0, 0]], dtype=np.float64),   # horizontal
    np.array([[0, -1, 0], [0, 0, 0], [0, 1, 0]], dtype=np.float64),   # vertical
    np.array([[-1, 0, 1], [0, 0, 0], [1, 0, -1]], dtype=np.float64),  # diagonal
]
SRM_TRUNCATION = 2.0


# ===== BRANCH 1: CLIP (Semantic Features) =================================

class CLIPFeatureExtractor:
    """Extract 768-dim L2-normalized embeddings from OpenCLIP ViT-L/14."""

    def __init__(self, model, preprocess, tokenizer, device: torch.device):
        self.model = model
        self.preprocess = preprocess
        self.tokenizer = tokenizer
        self.device = device

    def extract(self, pil_img: Image.Image) -> np.ndarray:
        """Return (768,) float32 embedding."""
        try:
            img_tensor = self.preprocess(pil_img).unsqueeze(0).to(self.device)
            with torch.inference_mode():
                features = self.model.encode_image(img_tensor)
                features = F.normalize(features, dim=-1)
            return features.squeeze(0).cpu().numpy().astype(np.float32)
        except Exception as e:
            logger.error(f"CLIP extraction failed: {e}")
            return np.zeros(768, dtype=np.float32)

    def get_similarities(self, pil_img: Image.Image) -> dict:
        """Return CLIP similarity scores against AI/Real text prompts."""
        real_prompts = [
            "a real photograph taken by a camera",
            "an authentic photograph with natural lighting",
            "a photo with realistic depth of field and natural noise",
            "a genuine unedited photograph of the real world",
            "a candid photo with natural motion and imperfections",
        ]
        ai_prompts = [
            "an AI generated image created by a neural network",
            "a synthetic image created by stable diffusion or midjourney",
            "a deepfake or computer generated image",
            "a photorealistic image generated by a GAN or diffusion model",
            "an artificially created scene with perfect symmetry",
        ]
        try:
            import open_clip
            img_tensor = self.preprocess(pil_img).unsqueeze(0).to(self.device)
            all_prompts = real_prompts + ai_prompts
            text_tokens = self.tokenizer(all_prompts).to(self.device)

            with torch.inference_mode():
                img_feat = self.model.encode_image(img_tensor)
                img_feat = F.normalize(img_feat, dim=-1)
                txt_feat = self.model.encode_text(text_tokens)
                txt_feat = F.normalize(txt_feat, dim=-1)
                sims = (img_feat @ txt_feat.T).squeeze(0).cpu().numpy()

            real_sim = float(np.mean(sims[:5]))
            ai_sim = float(np.mean(sims[5:]))
            return {
                "real_similarity": real_sim,
                "ai_similarity": ai_sim,
                "ratio": float(ai_sim / (real_sim + ai_sim + 1e-8)),
                "raw_sims": {p[:50]: float(s) for p, s in zip(all_prompts, sims)},
            }
        except Exception as e:
            logger.error(f"CLIP similarity failed: {e}")
            return {"real_similarity": 0.5, "ai_similarity": 0.5, "ratio": 0.5, "raw_sims": {}}


# ===== BRANCH 2: EfficientNet (Artifact Detection) ========================

class EfficientNetFeatureExtractor:
    """Extract 1280-dim intermediate features from EfficientNetV2-L via GAP."""

    def __init__(self, backbone, device: torch.device):
        self.backbone = backbone
        self.device = device

    def extract(self, pil_img: Image.Image) -> np.ndarray:
        """Return (1280,) float32 features from penultimate layer."""
        try:
            tensor = self._preprocess(pil_img)
            with torch.inference_mode():
                features = self.backbone(tensor)  # (1, 1280) with num_classes=0
            return features.squeeze(0).cpu().numpy().astype(np.float32)
        except Exception as e:
            logger.error(f"EfficientNet extraction failed: {e}")
            return np.zeros(1280, dtype=np.float32)

    def get_model(self):
        """Return the backbone model for GradCAM."""
        return self.backbone

    def _preprocess(self, pil_img: Image.Image) -> torch.Tensor:
        """PIL → (1, 3, 480, 480) normalized tensor."""
        img = pil_img.resize((480, 480), Image.LANCZOS)
        arr = np.array(img).astype(np.float32) / 255.0
        arr = (arr - IMAGENET_MEAN) / IMAGENET_STD
        tensor = torch.from_numpy(arr).permute(2, 0, 1).unsqueeze(0)
        return tensor.to(self.device)


# ===== BRANCH 3: FFT (Frequency Features) =================================

class FFTFeatureExtractor:
    """Extract frequency-domain statistics from 2D FFT magnitude spectrum."""

    @staticmethod
    def extract(pil_img: Image.Image) -> np.ndarray:
        """Return (8,) float32 feature vector."""
        try:
            np_img = np.array(pil_img.convert("L"))
            gray = cv2.resize(np_img, (512, 512), interpolation=cv2.INTER_AREA)

            # 2D FFT
            f_transform = np.fft.fft2(gray.astype(np.float64))
            f_shift = np.fft.fftshift(f_transform)
            magnitude = np.abs(f_shift) + 1e-8
            log_mag = np.log(magnitude)

            # Radial profile (azimuthal average)
            H, W = log_mag.shape
            cy, cx = H // 2, W // 2
            Y, X = np.mgrid[0:H, 0:W]
            R = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2)
            max_r = int(min(cx, cy))
            profile = []
            for r in range(0, max_r, 2):
                mask = (R >= r) & (R < r + 2)
                if mask.any():
                    profile.append(float(np.mean(log_mag[mask])))
            profile = np.array(profile) if profile else np.zeros(10)

            # Band decomposition
            n = len(profile)
            low = profile[: max(1, n // 5)]
            mid = profile[n // 5: 3 * n // 5]
            high = profile[3 * n // 5:]

            eps = 1e-8
            mean_mag = float(np.mean(log_mag))
            var_mag = float(np.var(log_mag))
            high_freq_energy = float(np.mean(high)) if len(high) > 0 else 0.0
            mid_freq_energy = float(np.mean(mid)) / (abs(float(np.mean(low))) + eps) if len(mid) > 0 else 0.0

            # Spectral flatness
            profile_pos = np.clip(np.exp(profile), eps, None)
            from scipy.stats import gmean
            geo = float(gmean(profile_pos)) if len(profile_pos) > 0 else eps
            arith = float(np.mean(profile_pos))
            spectral_flatness = geo / (arith + eps)

            # Periodicity via autocorrelation
            if len(profile) > 4:
                centered = profile - np.mean(profile)
                ac = np.correlate(centered, centered, mode="full")
                ac = ac[len(ac) // 2:]
                if ac[0] != 0:
                    ac = ac / ac[0]
                search = ac[2: min(20, len(ac))]
                periodicity = float(np.max(search)) if len(search) > 0 else 0.0
            else:
                periodicity = 0.0

            # High-to-low ratio
            high_low_ratio = float(np.mean(high)) / (abs(float(np.mean(low))) + eps) if len(high) > 0 and len(low) > 0 else 0.0

            # Peak prominence
            peak_prom = float(np.max(profile) - np.mean(profile))

            features = np.array([
                mean_mag,
                var_mag,
                high_freq_energy,
                mid_freq_energy,
                spectral_flatness,
                periodicity,
                high_low_ratio,
                peak_prom,
            ], dtype=np.float32)

            return features

        except Exception as e:
            logger.error(f"FFT extraction failed: {e}")
            return np.zeros(8, dtype=np.float32)

    @staticmethod
    def extract_spectrum_for_display(pil_img: Image.Image) -> dict:
        """Return spectrum data for frontend visualization."""
        try:
            np_img = np.array(pil_img.convert("L"))
            gray = cv2.resize(np_img, (512, 512), interpolation=cv2.INTER_AREA)
            f_transform = np.fft.fft2(gray.astype(np.float64))
            f_shift = np.fft.fftshift(f_transform)
            log_mag = np.log(np.abs(f_shift) + 1e-8)

            # Downsample for frontend
            small = cv2.resize(log_mag, (64, 64), interpolation=cv2.INTER_AREA)

            # Radial profile
            H, W = log_mag.shape
            cy, cx = H // 2, W // 2
            Y, X = np.mgrid[0:H, 0:W]
            R = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2)
            max_r = int(min(cx, cy))
            profile = []
            for r in range(0, max_r, 2):
                mask = (R >= r) & (R < r + 2)
                if mask.any():
                    profile.append(float(np.mean(log_mag[mask])))

            return {
                "spectrum_2d_small": small.tolist(),
                "profile_1d": profile,
            }
        except Exception:
            return {"spectrum_2d_small": [], "profile_1d": []}


# ===== BRANCH 4: SRM (Noise Residual Features) ============================

class SRMFeatureExtractor:
    """Extract noise residual statistics using SRM (Spatial Rich Model) filters."""

    @staticmethod
    def extract(pil_img: Image.Image) -> np.ndarray:
        """Return (15,) float32 feature vector."""
        try:
            np_img = np.array(pil_img.convert("RGB"))
            np_img = cv2.resize(np_img, (512, 512), interpolation=cv2.INTER_AREA)

            residuals = SRMFeatureExtractor._apply_filters(np_img)
            stats = SRMFeatureExtractor._compute_stats(residuals)
            return np.array(stats, dtype=np.float32)
        except Exception as e:
            logger.error(f"SRM extraction failed: {e}")
            return np.zeros(15, dtype=np.float32)

    @staticmethod
    def _apply_filters(np_img: np.ndarray) -> np.ndarray:
        """Apply 3 SRM filters × 3 channels → (H, W, 9)."""
        H, W, C = np_img.shape
        residuals = np.zeros((H, W, 9), dtype=np.float64)
        for f_idx, filt in enumerate(SRM_FILTERS):
            for c_idx in range(3):
                channel = np_img[:, :, c_idx].astype(np.float64)
                residual = cv2.filter2D(channel, -1, filt)
                residuals[:, :, f_idx * 3 + c_idx] = residual
        return np.clip(residuals, -SRM_TRUNCATION, SRM_TRUNCATION)

    @staticmethod
    def _compute_stats(residuals: np.ndarray) -> list:
        """Compute 15 statistical features from 9 residual channels.
        
        Per-channel: mean, std → 9×2 = 18 raw stats
        Aggregated into 15 summary features.
        """
        n_ch = residuals.shape[2]
        means, stds, kurts, skews, entropies = [], [], [], [], []

        for c in range(n_ch):
            ch = residuals[:, :, c].flatten()
            means.append(float(np.mean(ch)))
            stds.append(float(np.std(ch)))
            kurts.append(float(kurtosis(ch, fisher=True)))
            skews.append(float(skew(ch)))
            # Entropy: discretize residuals into histogram
            hist, _ = np.histogram(ch, bins=64, density=True)
            hist = hist + 1e-10
            entropies.append(float(sp_entropy(hist)))

        return [
            float(np.mean(means)),       # 0: avg mean across channels
            float(np.std(means)),        # 1: std of means
            float(np.mean(stds)),        # 2: avg std
            float(np.std(stds)),         # 3: std of stds
            float(np.mean(kurts)),       # 4: avg kurtosis
            float(np.std(kurts)),        # 5: std of kurtosis
            float(np.max(kurts)),        # 6: max kurtosis
            float(np.min(kurts)),        # 7: min kurtosis
            float(np.mean(skews)),       # 8: avg skewness
            float(np.std(skews)),        # 9: std skewness
            float(np.mean(entropies)),   # 10: avg entropy
            float(np.std(entropies)),    # 11: std entropy
            float(np.median(stds)),      # 12: median std
            float(np.max(stds)),         # 13: max std
            float(np.mean([abs(s) for s in skews])),  # 14: mean abs skewness
        ]


# ===== MULTI-BRANCH COMBINER ===============================================

class MultiFeatureExtractor:
    """Orchestrates all 4 branches, normalizes, optionally applies PCA, concatenates.
    
    Feature vector layout:
      [0:768]      CLIP embedding (768-dim, or 128 after PCA)
      [768:2048]   EfficientNet features (1280-dim, or 128 after PCA)
      [2048:2056]  FFT features (8-dim)
      [2056:2071]  SRM features (15-dim)
    """

    def __init__(
        self,
        clip_extractor: Optional[CLIPFeatureExtractor] = None,
        effnet_extractor: Optional[EfficientNetFeatureExtractor] = None,
        use_pca: bool = True,
        pca_dims: dict = None,
    ):
        self.clip_ext = clip_extractor
        self.effnet_ext = effnet_extractor
        self.fft_ext = FFTFeatureExtractor()
        self.srm_ext = SRMFeatureExtractor()
        self.use_pca = use_pca
        self.pca_dims = pca_dims or {"clip": 128, "effnet": 128}

        # Per-block scalers (fitted during training)
        self.scalers = {}      # block_name → StandardScaler
        self.pca_models = {}   # block_name → PCA

    def extract_raw(self, pil_img: Image.Image) -> dict:
        """Extract raw features from all 4 branches. Returns dict of arrays."""
        pil_img = pil_img.convert("RGB")

        blocks = {}
        # CLIP
        if self.clip_ext is not None:
            blocks["clip"] = self.clip_ext.extract(pil_img)
        else:
            blocks["clip"] = np.zeros(768, dtype=np.float32)

        # EfficientNet
        if self.effnet_ext is not None:
            blocks["effnet"] = self.effnet_ext.extract(pil_img)
        else:
            blocks["effnet"] = np.zeros(1280, dtype=np.float32)

        # FFT
        blocks["fft"] = self.fft_ext.extract(pil_img)

        # SRM
        blocks["srm"] = self.srm_ext.extract(pil_img)

        return blocks

    def extract(self, pil_img: Image.Image) -> np.ndarray:
        """Extract, normalize, PCA, concatenate → single feature vector."""
        blocks = self.extract_raw(pil_img)
        return self._process_blocks(blocks)

    def extract_batch_raw(self, images: list) -> list:
        """Extract raw features for a batch of PIL images."""
        return [self.extract_raw(img) for img in images]

    def fit_scalers(self, all_blocks: list):
        """Fit StandardScalers and PCA on training feature blocks.
        
        Args:
            all_blocks: list of dicts from extract_raw()
        """
        from sklearn.preprocessing import StandardScaler
        from sklearn.decomposition import PCA

        block_names = ["clip", "effnet", "fft", "srm"]
        for name in block_names:
            features = np.stack([b[name] for b in all_blocks])
            scaler = StandardScaler()
            scaler.fit(features)
            self.scalers[name] = scaler

            if self.use_pca and name in self.pca_dims:
                n_components = min(self.pca_dims[name], features.shape[1], features.shape[0])
                pca = PCA(n_components=n_components, random_state=42)
                scaled = scaler.transform(features)
                pca.fit(scaled)
                self.pca_models[name] = pca
                logger.info(f"  PCA {name}: {features.shape[1]} → {n_components} dims "
                           f"(explained variance: {pca.explained_variance_ratio_.sum():.3f})")

    def _process_blocks(self, blocks: dict) -> np.ndarray:
        """Normalize + PCA + concat a single sample's blocks."""
        parts = []
        for name in ["clip", "effnet", "fft", "srm"]:
            vec = blocks[name].reshape(1, -1)

            if name in self.scalers:
                vec = self.scalers[name].transform(vec)

            if name in self.pca_models:
                vec = self.pca_models[name].transform(vec)

            parts.append(vec.flatten())

        return np.concatenate(parts).astype(np.float32)

    def process_batch(self, all_blocks: list) -> np.ndarray:
        """Normalize + PCA + concat for a batch."""
        return np.stack([self._process_blocks(b) for b in all_blocks])

    def get_feature_dim(self) -> int:
        """Return total feature vector dimension after PCA."""
        clip_d = self.pca_dims.get("clip", 768) if self.use_pca and "clip" in self.pca_models else 768
        effnet_d = self.pca_dims.get("effnet", 1280) if self.use_pca and "effnet" in self.pca_models else 1280
        return clip_d + effnet_d + 8 + 15  # FFT=8, SRM=15

    def save(self, path: str):
        """Save scalers and PCA models."""
        data = {
            "scalers": self.scalers,
            "pca_models": self.pca_models,
            "use_pca": self.use_pca,
            "pca_dims": self.pca_dims,
        }
        with open(path, "wb") as f:
            pickle.dump(data, f)
        logger.info(f"Saved feature processor to {path}")

    def load(self, path: str):
        """Load scalers and PCA models."""
        with open(path, "rb") as f:
            data = pickle.load(f)
        self.scalers = data.get("scalers", {})
        self.pca_models = data.get("pca_models", {})
        self.use_pca = data.get("use_pca", True)
        self.pca_dims = data.get("pca_dims", {"clip": 128, "effnet": 128})
        logger.info(f"Loaded feature processor from {path}")
